// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/children/add": {
            "post": {
                "description": "ผู้ปกครองเพิ่มข้อมูลเด็กใหม่ (ต้องล็อกอินก่อน)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Children"
                ],
                "summary": "เพิ่มข้อมูลเด็กใหม่",
                "parameters": [
                    {
                        "description": "ข้อมูลเด็กใหม่",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/childrenController.AddChildrenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "เพิ่มข้อมูลเด็กสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "ไม่ได้รับอนุญาต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "ระบบขัดข้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/children/delete/{id}": {
            "delete": {
                "description": "ลบข้อมูลเด็กตาม ID (ต้องเป็น parent ของเด็กคนนั้น)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Children"
                ],
                "summary": "ลบข้อมูลเด็ก",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Child ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ลบข้อมูลเด็กสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "ไอดีเด็กไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "ไม่ได้รับอนุญาต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "ไม่พบข้อมูลเด็ก",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "ระบบขัดข้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/children/get": {
            "get": {
                "description": "ดึงข้อมูลเด็กทั้งหมดที่เป็นลูกของผู้ปกครอง (ต้องล็อกอินก่อน)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Children"
                ],
                "summary": "ดึงข้อมูลเด็กทั้งหมดของผู้ใช้",
                "responses": {
                    "200": {
                        "description": "รายการเด็ก",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "ไม่ได้รับอนุญาต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "ไม่พบข้อมูลเด็ก",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "ระบบขัดข้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/children/get/{id}": {
            "get": {
                "description": "ดึงข้อมูลเด็กคนเดียว โดยตรวจสอบว่าเป็นลูกของผู้ใช้ (ต้องล็อกอินก่อน)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Children"
                ],
                "summary": "ดึงข้อมูลเด็กตาม ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Child ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ข้อมูลเด็ก",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ไอดีเด็กไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "ไม่ได้รับอนุญาต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "ไม่พบข้อมูลเด็ก",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/children/update/{id}": {
            "put": {
                "description": "อัปเดตข้อมูลเด็กตาม ID (ต้องเป็น parent ของเด็กคนนั้น)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Children"
                ],
                "summary": "อัปเดตข้อมูลเด็ก",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Child ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ข้อมูลเด็กที่จะอัปเดต",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/childrenController.UpdateChildrenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "อัปเดตข้อมูลเด็กสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "ไม่ได้รับอนุญาต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "ไม่พบข้อมูลเด็ก",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metaAgeRange/add": {
            "post": {
                "description": "ใช้สำหรับเพิ่มข้อมูลช่วงอายุ (admin เท่านั้น)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MetaAgeRange"
                ],
                "summary": "เพิ่มช่วงอายุใหม่",
                "parameters": [
                    {
                        "description": "ข้อมูลช่วงอายุ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metadataController.AddAgeRangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/metaAgeRange/delete/{id}": {
            "delete": {
                "description": "ลบข้อมูลช่วงอายุ (admin เท่านั้น)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MetaAgeRange"
                ],
                "summary": "ลบช่วงอายุตาม ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ObjectID ของช่วงอายุ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/metaAgeRange/get-all": {
            "get": {
                "description": "คืนค่าข้อมูลช่วงอายุทั้งหมด (admin เท่านั้น)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MetaAgeRange"
                ],
                "summary": "ดึงข้อมูลช่วงอายุทั้งหมด",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/metadataModel.MetaAgeRange"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/metaAgeRange/get/{id}": {
            "get": {
                "description": "คืนค่าข้อมูลช่วงอายุตาม ObjectID (admin เท่านั้น)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MetaAgeRange"
                ],
                "summary": "ดึงข้อมูลช่วงอายุตาม ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ObjectID ของช่วงอายุ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/metadataModel.MetaAgeRange"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/metaAgeRange/update/{id}": {
            "put": {
                "description": "ใช้สำหรับอัปเดตข้อมูลช่วงอายุ (admin เท่านั้น)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MetaAgeRange"
                ],
                "summary": "อัปเดตช่วงอายุตาม ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ObjectID ของช่วงอายุ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ข้อมูลใหม่",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metadataModel.MetaAgeRange"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/metadataModel.MetaAgeRange"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/all": {
            "get": {
                "description": "ดึงข้อมูลผู้ใช้ทั้งหมด (เฉพาะ admin เท่านั้น)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "ดึงข้อมูลผู้ใช้ทั้งหมด",
                "responses": {
                    "200": {
                        "description": "ดึงข้อมูลผู้ใช้สำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "ไม่ได้รับอนุญาต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/assign-role": {
            "put": {
                "description": "เปลี่ยน role ของผู้ใช้ (admin เท่านั้น)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "กำหนดสิทธิ์ผู้ใช้",
                "parameters": [
                    {
                        "description": "Target user ID และ Role ใหม่",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userController.assignRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "อัปเดต role สำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "ไม่ได้รับอนุญาต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "ผู้ใช้เข้าสู่ระบบด้วยอีเมลและรหัสผ่าน จากนั้นระบบจะส่ง JWT token กลับมา",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "เข้าสู่ระบบ",
                "parameters": [
                    {
                        "description": "ข้อมูลเข้าสู่ระบบ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userController.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "เข้าสู่ระบบสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "รหัสผ่านไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "ไม่พบผู้ใช้งาน",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "ข้อผิดพลาดจากเซิร์ฟเวอร์",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "description": "ลบ JWT cookie ออกจากระบบ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "ออกจากระบบ",
                "responses": {
                    "200": {
                        "description": "ออกจากระบบสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "ข้อผิดพลาดจากเซิร์ฟเวอร์",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/reset-password": {
            "put": {
                "description": "รีเซ็ตรหัสผ่านใหม่ โดยตรวจสอบรหัสผ่านเก่า",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "เปลี่ยนรหัสผ่าน",
                "parameters": [
                    {
                        "description": "รหัสผ่านเก่าและรหัสผ่านใหม่",
                        "name": "passwords",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userController.resetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "รหัสผ่านถูกอัปเดตสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "รหัสผ่านเก่าไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "description": "สร้างบัญชีผู้ใช้ใหม่",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "สมัครสมาชิก",
                "parameters": [
                    {
                        "description": "User signup data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userController.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "สมัครสมาชิกสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "เกิดข้อผิดพลาดจากเซิร์ฟเวอร์",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/update": {
            "put": {
                "description": "อัปเดตข้อมูลผู้ใช้ (ชื่อ, นามสกุล, อีเมล, รูปภาพ)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "อัปเดตโปรไฟล์",
                "parameters": [
                    {
                        "description": "ข้อมูลที่ต้องการอัปเดต",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userController.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "โปรไฟล์อัปเดตสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "ไม่ได้รับอนุญาต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "childrenController.AddChildrenRequest": {
            "type": "object",
            "properties": {
                "birthDate": {
                    "type": "string",
                    "example": "2020-05-01T00:00:00Z"
                },
                "firstName": {
                    "type": "string",
                    "example": "สมชาย"
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "image": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
                },
                "lastName": {
                    "type": "string",
                    "example": "ใจดี"
                }
            }
        },
        "childrenController.UpdateChildrenRequest": {
            "type": "object",
            "properties": {
                "birthDate": {
                    "type": "string",
                    "example": "2020-05-01T00:00:00Z"
                },
                "firstName": {
                    "type": "string",
                    "example": "สมหมาย"
                },
                "gender": {
                    "type": "string",
                    "example": "female"
                },
                "image": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
                },
                "lastName": {
                    "type": "string",
                    "example": "ใจดี"
                }
            }
        },
        "metadataController.AddAgeRangeRequest": {
            "type": "object",
            "required": [
                "ageRange"
            ],
            "properties": {
                "ageRange": {
                    "type": "integer",
                    "example": 24
                }
            }
        },
        "metadataModel.MetaAgeRange": {
            "type": "object",
            "properties": {
                "ageRange": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "userController.assignRoleRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ],
                    "example": "user"
                },
                "targetId": {
                    "type": "string"
                }
            }
        },
        "userController.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@mail.com"
                },
                "password": {
                    "type": "string",
                    "example": "strongpassword123"
                }
            }
        },
        "userController.registerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@mail.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "password": {
                    "type": "string",
                    "example": "strongpassword123"
                }
            }
        },
        "userController.resetPasswordRequest": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string",
                    "example": "newstrongpassword123"
                },
                "oldPassword": {
                    "type": "string",
                    "example": "strongpassword123"
                },
                "repeatNewPassword": {
                    "type": "string",
                    "example": "newstrongpassword123"
                }
            }
        },
        "userController.updateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "newemail@mail.com"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "picture": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "MimiCare API",
	Description:      "Backend API for MimiCare Project (Gin + MongoDB)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
