basePath: /api/v1
definitions:
  userController.assignRoleRequest:
    properties:
      role:
        enum:
        - user
        - admin
        example: user
        type: string
      targetId:
        type: string
    type: object
  userController.loginRequest:
    properties:
      email:
        example: example@mail.com
        type: string
      password:
        example: strongpassword123
        type: string
    type: object
  userController.registerRequest:
    properties:
      email:
        example: example@mail.com
        type: string
      firstName:
        example: John
        type: string
      lastName:
        example: Doe
        type: string
      password:
        example: strongpassword123
        type: string
    type: object
  userController.resetPasswordRequest:
    properties:
      newPassword:
        example: newstrongpassword123
        type: string
      oldPassword:
        example: strongpassword123
        type: string
      repeatNewPassword:
        example: newstrongpassword123
        type: string
    type: object
  userController.updateRequest:
    properties:
      email:
        example: newemail@mail.com
        type: string
      firstName:
        example: John
        type: string
      lastName:
        example: Doe
        type: string
      picture:
        example: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  description: Backend API for MimiCare Project (Gin + MongoDB)
  title: MimiCare API
  version: "1.0"
paths:
  /user/all:
    get:
      description: ดึงข้อมูลผู้ใช้ทั้งหมด (เฉพาะ admin เท่านั้น)
      produces:
      - application/json
      responses:
        "200":
          description: ดึงข้อมูลผู้ใช้สำเร็จ
          schema:
            additionalProperties: true
            type: object
        "403":
          description: ไม่ได้รับอนุญาต
          schema:
            additionalProperties: true
            type: object
      summary: ดึงข้อมูลผู้ใช้ทั้งหมด
      tags:
      - Auth
  /user/assign-role:
    put:
      consumes:
      - application/json
      description: เปลี่ยน role ของผู้ใช้ (admin เท่านั้น)
      parameters:
      - description: Target user ID และ Role ใหม่
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/userController.assignRoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: อัปเดต role สำเร็จ
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ข้อมูลไม่ถูกต้อง
          schema:
            additionalProperties: true
            type: object
        "403":
          description: ไม่ได้รับอนุญาต
          schema:
            additionalProperties: true
            type: object
      summary: กำหนดสิทธิ์ผู้ใช้
      tags:
      - Auth
  /user/login:
    post:
      consumes:
      - application/json
      description: ผู้ใช้เข้าสู่ระบบด้วยอีเมลและรหัสผ่าน จากนั้นระบบจะส่ง JWT token
        กลับมา
      parameters:
      - description: ข้อมูลเข้าสู่ระบบ
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/userController.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: เข้าสู่ระบบสำเร็จ
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ข้อมูลไม่ถูกต้อง
          schema:
            additionalProperties: true
            type: object
        "401":
          description: รหัสผ่านไม่ถูกต้อง
          schema:
            additionalProperties: true
            type: object
        "404":
          description: ไม่พบผู้ใช้งาน
          schema:
            additionalProperties: true
            type: object
        "500":
          description: ข้อผิดพลาดจากเซิร์ฟเวอร์
          schema:
            additionalProperties: true
            type: object
      summary: เข้าสู่ระบบ
      tags:
      - Auth
  /user/logout:
    post:
      description: ลบ JWT cookie ออกจากระบบ
      produces:
      - application/json
      responses:
        "200":
          description: ออกจากระบบสำเร็จ
          schema:
            additionalProperties: true
            type: object
        "500":
          description: ข้อผิดพลาดจากเซิร์ฟเวอร์
          schema:
            additionalProperties: true
            type: object
      summary: ออกจากระบบ
      tags:
      - Auth
  /user/reset-password:
    put:
      consumes:
      - application/json
      description: รีเซ็ตรหัสผ่านใหม่ โดยตรวจสอบรหัสผ่านเก่า
      parameters:
      - description: รหัสผ่านเก่าและรหัสผ่านใหม่
        in: body
        name: passwords
        required: true
        schema:
          $ref: '#/definitions/userController.resetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: รหัสผ่านถูกอัปเดตสำเร็จ
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ข้อมูลไม่ถูกต้อง
          schema:
            additionalProperties: true
            type: object
        "401":
          description: รหัสผ่านเก่าไม่ถูกต้อง
          schema:
            additionalProperties: true
            type: object
      summary: เปลี่ยนรหัสผ่าน
      tags:
      - Auth
  /user/signup:
    post:
      consumes:
      - application/json
      description: สร้างบัญชีผู้ใช้ใหม่
      parameters:
      - description: User signup data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/userController.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: สมัครสมาชิกสำเร็จ
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ข้อมูลไม่ถูกต้อง
          schema:
            additionalProperties: true
            type: object
        "500":
          description: เกิดข้อผิดพลาดจากเซิร์ฟเวอร์
          schema:
            additionalProperties: true
            type: object
      summary: สมัครสมาชิก
      tags:
      - Auth
  /user/update:
    put:
      consumes:
      - application/json
      description: อัปเดตข้อมูลผู้ใช้ (ชื่อ, นามสกุล, อีเมล, รูปภาพ)
      parameters:
      - description: ข้อมูลที่ต้องการอัปเดต
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/userController.updateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: โปรไฟล์อัปเดตสำเร็จ
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ข้อมูลไม่ถูกต้อง
          schema:
            additionalProperties: true
            type: object
        "403":
          description: ไม่ได้รับอนุญาต
          schema:
            additionalProperties: true
            type: object
      summary: อัปเดตโปรไฟล์
      tags:
      - Auth
schemes:
- http
swagger: "2.0"
